[18-08-08] [ENTRY]: [Nathan]
[18-08-08] [THREAD STARTED]: Singular Cyder Instance Ensurer
[18-08-09] [THREAD STARTED]: Splash Loader
[18-08-09] [SYSTEM_IO]: Unable to create all userfiles for user [7d7ebb00-81fe-329f-8a78-62f463d0b7da] after 1000 attempts [4x]
[18-08-09] [SYSTEM_IO]: Created temperatory file: 18-08-09.stacktrace
[18-08-09] [EXCEPTION]:
Exception origin: cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:488)
From line: 488
Trace: java.lang.NullPointerException
at cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:488)
at cyder.utilities.UserUtil.validateAllusers(UserUtil.java:566)
at cyder.genesis.Cyder.main(Cyder.java:96)
[18-08-09] [SYSTEM_IO]: File already existed in userspace: 18-08-09.stacktrace
[18-08-09] [EXCEPTION]:
Exception origin: cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:488)
From line: 488
Trace: java.lang.NullPointerException
at cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:488)
at cyder.utilities.UserUtil.validateAllusers(UserUtil.java:566)
at cyder.genesis.Cyder.main(Cyder.java:96)
[18-08-09] [SYSTEM_IO]: File already existed in userspace: 18-08-09.stacktrace
[18-08-09] [EXCEPTION]:
Exception origin: cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:488)
From line: 488
Trace: java.lang.NullPointerException
at cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:488)
at cyder.utilities.UserUtil.validateAllusers(UserUtil.java:566)
at cyder.genesis.Cyder.main(Cyder.java:96)
[18-08-09] [SYSTEM_IO]: File already existed in userspace: 18-08-09.stacktrace
[18-08-09] [EXCEPTION]:
Exception origin: cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:488)
From line: 488
Trace: java.lang.NullPointerException
at cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:488)
at cyder.utilities.UserUtil.validateAllusers(UserUtil.java:566)
at cyder.genesis.Cyder.main(Cyder.java:96)
[18-08-09] [SYSTEM_IO]: File already existed in userspace: 18-08-09.stacktrace
[18-08-09] [EXCEPTION]:
Exception origin: cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:488)
From line: 488
Trace: java.lang.NullPointerException
at cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:488)
at cyder.utilities.UserUtil.validateAllusers(UserUtil.java:566)
at cyder.genesis.Cyder.main(Cyder.java:96)
[18-08-09] [SYSTEM_IO]: File already existed in userspace: 18-08-09.stacktrace
[18-08-09] [EXCEPTION]:
Exception origin: cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:488)
From line: 488
Trace: java.lang.NullPointerException
at cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:488)
at cyder.utilities.UserUtil.validateAllusers(UserUtil.java:566)
at cyder.genesis.Cyder.main(Cyder.java:96)
[18-08-09] [SYSTEM_IO]: File already existed in userspace: 18-08-09.stacktrace
[18-08-09] [EXCEPTION]:
Exception origin: cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:488)
From line: 488
Trace: java.lang.NullPointerException
at cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:488)
at cyder.utilities.UserUtil.validateAllusers(UserUtil.java:566)
at cyder.genesis.Cyder.main(Cyder.java:96)
[18-08-09] [SYSTEM_IO]: File already existed in userspace: 18-08-09.stacktrace
[18-08-09] [EXCEPTION]:
Exception origin: cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:488)
From line: 488
Trace: java.lang.NullPointerException
at cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:488)
at cyder.utilities.UserUtil.validateAllusers(UserUtil.java:566)
at cyder.genesis.Cyder.main(Cyder.java:96)
[18-08-09] [SYSTEM_IO]: File already existed in userspace: 18-08-09.stacktrace
[18-08-09] [EXCEPTION]:
Exception origin: cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:488)
From line: 488
Trace: java.lang.NullPointerException
at cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:488)
at cyder.utilities.UserUtil.validateAllusers(UserUtil.java:566)
at cyder.genesis.Cyder.main(Cyder.java:96)
[18-08-09] [SYSTEM_IO]: File already existed in userspace: 18-08-09.stacktrace
[18-08-09] [THREAD STARTED]: Splash Animation
[18-08-09] [EXCEPTION]:
Exception origin: cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:488)
From line: 488
Trace: java.lang.NullPointerException
at cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:488)
at cyder.utilities.UserUtil.validateAllusers(UserUtil.java:566)
at cyder.genesis.Cyder.main(Cyder.java:96)
[18-08-09] [CORRUPTION]: [BACKUP SUCCESS] Successfully restored 7d7ebb00-81fe-329f-8a78-62f463d0b7da from: 7d7ebb00-81fe-329f-8a78-62f463d0b7da_1646787699135
[18-08-10] [THREAD STARTED]: Cyder Start Secondary Subroutines
[18-08-10] [LOGIN]: [AUTOCYPHER ATTEMPT]
[18-08-10] [THREAD STARTED]: JVM Logger
[18-08-10] [ACTION]: Requested deletion of: C:\Users\Nathan\Documents\IntelliJava\Cyder\dynamic\tmp
[18-08-10] [LOGIN]: [[AUTOCYPHER PASS]: 7d7ebb00-81fe-329f-8a78-62f463d0b7da]
[18-08-10] [SYSTEM_IO]: Userdata requested: RandomBackground
[18-08-10] [SYSTEM_IO]: Created temperatory file: 18-08-10.stacktrace
[18-08-10] [EXCEPTION]:
Exception origin: cyder.utilities.ColorUtil.hexToRgb(ColorUtil.java:31)
From line: 31
Trace: java.lang.NullPointerException
at cyder.utilities.ColorUtil.hexToRgb(ColorUtil.java:31)
at cyder.ui.ConsoleFrame.launch(ConsoleFrame.java:272)
at cyder.handlers.internal.LoginHandler.recognize(LoginHandler.java:513)
at cyder.handlers.internal.LoginHandler.autoCypher(LoginHandler.java:553)
at cyder.handlers.internal.LoginHandler.determineCyderEntry(LoginHandler.java:447)
at cyder.genesis.Cyder.main(Cyder.java:119)
[18-08-10] [SYSTEM_IO]: Userdata requested: SilenceErrors
[18-09-01] [ACTION]: CyderFrame disposed with fastclose: true, CyderFrame: Component name = [cyder.ui.CyderFrame], bounds = [(980, 396, 600, 600)], hash = [1403650964], parentFrame = [Object itself is the top level frame], associated text = [No getText() method found], tooltip text = [No getTooltipText() method found], title = [Cyder Splash]
[18-09-01] [THREAD STARTED]: Cyder Splash CyderFrame dispose thread
[18-10-09] [EOL]: Log completed, Cyder crashed unexpectedly: exit code: -9 External Stop, exceptions thrown: 11
