[14-03-11] [ENTRY]: [Nathan]
[14-03-11] [SYSTEM_IO]: System data pared in IOUtil's static block
[14-03-11] [SYSTEM_IO]: Suggestions pared in IOUtil's static block
[14-03-11] [SYSTEM_IO]: Exit conditions pared in IOUtil's static block
[14-03-11] [SYSTEM_IO]: DebugHashes pared in IOUtil's static block
[14-03-13] [LOGIN]: [AUTOCYPHER ATTEMPT]
[14-03-13] [JAVA ARGS]: [LOCATION] [La casa de Nathan]
[14-03-14] [EXCEPTION]: 
Exception origin: cyder.utilities.UserUtil.extractUser(UserUtil.java:392)
From line: 392
Trace: java.lang.IllegalArgumentException: Provided file does not exist
	at cyder.utilities.UserUtil.extractUser(UserUtil.java:392)
	at cyder.ui.CyderFrame.<init>(CyderFrame.java:119)
	at cyder.handlers.internal.PopupHandler.inform(PopupHandler.java:46)
	at cyder.handlers.internal.PopupHandler.inform(PopupHandler.java:26)
	at cyder.handlers.internal.PopupHandler.inform(PopupHandler.java:22)
	at cyder.utilities.UserUtil.userJsonDeleted(UserUtil.java:919)
	at cyder.utilities.UserUtil.fixUser(UserUtil.java:227)
	at cyder.ui.ConsoleFrame.setUUID(ConsoleFrame.java:1685)
	at cyder.utilities.UserUtil.checkPassword(UserUtil.java:631)
	at cyder.handlers.internal.LoginHandler.recognize(LoginHandler.java:393)
	at cyder.handlers.internal.LoginHandler.autoCypher(LoginHandler.java:468)
	at cyder.handlers.internal.LoginHandler.beginLogin(LoginHandler.java:365)
	at cyder.genesis.Cyder.main(Cyder.java:112)
[14-03-14] [CORRUPTION]: userdir saved to: [Resulting Popup]
Unfortunately a user's data file was corrupted and had to be deleted. The following files still exists and are associated with the user at the following path:<br/>Cyder/dynamic/5311eb9d-7193-3a3c-bc7b-6fac990dec4f<br/>Files:<br/>Default
[14-03-14] [EXCEPTION]: 
Exception origin: cyder.utilities.UserUtil.getUserData(UserUtil.java:454)
From line: 454
Trace: java.lang.IllegalArgumentException: userdata.json does not exist
	at cyder.utilities.UserUtil.getUserData(UserUtil.java:454)
	at cyder.ui.ConsoleFrame.setUUID(ConsoleFrame.java:1687)
	at cyder.utilities.UserUtil.checkPassword(UserUtil.java:631)
	at cyder.handlers.internal.LoginHandler.recognize(LoginHandler.java:393)
	at cyder.handlers.internal.LoginHandler.autoCypher(LoginHandler.java:468)
	at cyder.handlers.internal.LoginHandler.beginLogin(LoginHandler.java:365)
	at cyder.genesis.Cyder.main(Cyder.java:112)
[14-03-14] [EXCEPTION]: 
Exception origin: cyder.utilities.UserUtil.setUserData(UserUtil.java:123)
From line: 123
Trace: java.lang.IllegalArgumentException: File does not exist
	at cyder.utilities.UserUtil.setUserData(UserUtil.java:123)
	at cyder.handlers.internal.LoginHandler.recognize(LoginHandler.java:398)
	at cyder.handlers.internal.LoginHandler.autoCypher(LoginHandler.java:468)
	at cyder.handlers.internal.LoginHandler.beginLogin(LoginHandler.java:365)
	at cyder.genesis.Cyder.main(Cyder.java:112)
[14-03-14] [LOGIN]: [AUTOCYPHER FAIL]
[14-03-14] [WIDGET OPENED]: LOGIN
[14-03-37] [EOL]: Log completed, Cyder was force closed by an external entity: exit code: -200 [External Stop], exceptions thrown: 3