[14-21-09] [ENTRY]: [Nathan]
[14-21-09] [SYSTEM_IO]: System data pared in IOUtil's static block
[14-21-09] [SYSTEM_IO]: Suggestions pared in IOUtil's static block
[14-21-09] [SYSTEM_IO]: Exit conditions pared in IOUtil's static block
[14-21-09] [SYSTEM_IO]: DebugHashes pared in IOUtil's static block
[14-21-10] [EXCEPTION]: 
Exception origin: cyder.utilities.UserUtil.updateOldJson(UserUtil.java:763)
From line: 763
Trace: java.lang.NullPointerException
	at cyder.utilities.UserUtil.updateOldJson(UserUtil.java:763)
	at cyder.utilities.IOUtil.fixUsers(IOUtil.java:386)
	at cyder.genesis.Cyder.main(Cyder.java:93)
[14-21-10] [CORRUPTION]: userdir saved to: [Resulting Popup]
Unfortunately a user's data file was corrupted and had to be deleted. The following files still exists and are associated with the user at the following path:<br/>Cyder/dynamic/0d3b4529-3192-3503-a843-63fdbfcd74f8<br/>Files:<br/>Default
[14-21-11] [LOGIN]: [AUTOCYPHER ATTEMPT]
[14-21-11] [JAVA ARGS]: [LOCATION] [La casa de Nathan]
[14-21-11] [EXCEPTION]: 
Exception origin: cyder.utilities.UserUtil.extractUser(UserUtil.java:398)
From line: 398
Trace: java.lang.IllegalArgumentException: Provided file does not exist
	at cyder.utilities.UserUtil.extractUser(UserUtil.java:398)
	at cyder.ui.CyderFrame.<init>(CyderFrame.java:119)
	at cyder.handlers.internal.PopupHandler.inform(PopupHandler.java:46)
	at cyder.handlers.internal.PopupHandler.inform(PopupHandler.java:26)
	at cyder.handlers.internal.PopupHandler.inform(PopupHandler.java:22)
	at cyder.utilities.UserUtil.userJsonDeleted(UserUtil.java:925)
	at cyder.utilities.UserUtil.fixUser(UserUtil.java:227)
	at cyder.ui.ConsoleFrame.setUUID(ConsoleFrame.java:1693)
	at cyder.utilities.UserUtil.checkPassword(UserUtil.java:637)
	at cyder.handlers.internal.LoginHandler.recognize(LoginHandler.java:393)
	at cyder.handlers.internal.LoginHandler.autoCypher(LoginHandler.java:468)
	at cyder.handlers.internal.LoginHandler.beginLogin(LoginHandler.java:365)
	at cyder.genesis.Cyder.main(Cyder.java:112)
[14-21-11] [CORRUPTION]: userdir saved to: [Resulting Popup]
Unfortunately a user's data file was corrupted and had to be deleted. The following files still exists and are associated with the user at the following path:<br/>Cyder/dynamic/0d3b4529-3192-3503-a843-63fdbfcd74f8<br/>Files:<br/>Default
[14-21-11] [EXCEPTION]: 
Exception origin: cyder.utilities.UserUtil.getUserData(UserUtil.java:460)
From line: 460
Trace: java.lang.IllegalArgumentException: userdata.json does not exist
	at cyder.utilities.UserUtil.getUserData(UserUtil.java:460)
	at cyder.ui.ConsoleFrame.setUUID(ConsoleFrame.java:1695)
	at cyder.utilities.UserUtil.checkPassword(UserUtil.java:637)
	at cyder.handlers.internal.LoginHandler.recognize(LoginHandler.java:393)
	at cyder.handlers.internal.LoginHandler.autoCypher(LoginHandler.java:468)
	at cyder.handlers.internal.LoginHandler.beginLogin(LoginHandler.java:365)
	at cyder.genesis.Cyder.main(Cyder.java:112)
[14-21-11] [EXCEPTION]: 
Exception origin: cyder.utilities.UserUtil.setUserData(UserUtil.java:123)
From line: 123
Trace: java.lang.IllegalArgumentException: File does not exist
	at cyder.utilities.UserUtil.setUserData(UserUtil.java:123)
	at cyder.handlers.internal.LoginHandler.recognize(LoginHandler.java:398)
	at cyder.handlers.internal.LoginHandler.autoCypher(LoginHandler.java:468)
	at cyder.handlers.internal.LoginHandler.beginLogin(LoginHandler.java:365)
	at cyder.genesis.Cyder.main(Cyder.java:112)
[14-21-11] [LOGIN]: [AUTOCYPHER FAIL]
[14-21-11] [WIDGET OPENED]: LOGIN
[14-22-13] [EOL]: Log completed, Cyder was force closed by an external entity: exit code: -200 [External Stop], exceptions thrown: 4