[14-45-11] [ENTRY]: [Nathan]
[14-45-12] [SYSTEM_IO]: System data pared in IOUtil's static block
[14-45-12] [SYSTEM_IO]: Suggestions pared in IOUtil's static block
[14-45-12] [SYSTEM_IO]: Exit conditions pared in IOUtil's static block
[14-45-12] [SYSTEM_IO]: DebugHashes pared in IOUtil's static block
[14-45-12] [EXCEPTION]: 
Exception origin: cyder.utilities.UserUtil.updateOldJson(UserUtil.java:773)
From line: 773
Trace: java.lang.NullPointerException
	at cyder.utilities.UserUtil.updateOldJson(UserUtil.java:773)
	at cyder.utilities.IOUtil.fixUsers(IOUtil.java:386)
	at cyder.genesis.Cyder.main(Cyder.java:93)
[14-45-13] [CORRUPTION]: userdir saved to: [Resulting Popup]
Unfortunately a user's data file was corrupted and had to be deleted. The following files still exists and are associated with the user at the following path:<br/>Cyder/dynamic/5be8c384-7e7d-3540-a615-df8a3cd22bf9<br/>Files:<br/>Default
[14-45-14] [LOGIN]: [AUTOCYPHER ATTEMPT]
[14-45-14] [JAVA ARGS]: [LOCATION] [La casa de Nathan]
[14-45-14] [EXCEPTION]: 
Exception origin: cyder.utilities.UserUtil.extractUser(UserUtil.java:407)
From line: 407
Trace: java.lang.IllegalArgumentException: Provided file does not exist
	at cyder.utilities.UserUtil.extractUser(UserUtil.java:407)
	at cyder.ui.CyderFrame.<init>(CyderFrame.java:119)
	at cyder.handlers.internal.PopupHandler.inform(PopupHandler.java:46)
	at cyder.handlers.internal.PopupHandler.inform(PopupHandler.java:26)
	at cyder.handlers.internal.PopupHandler.inform(PopupHandler.java:22)
	at cyder.utilities.UserUtil.userJsonDeleted(UserUtil.java:935)
	at cyder.utilities.UserUtil.fixUser(UserUtil.java:227)
	at cyder.ui.ConsoleFrame.setUUID(ConsoleFrame.java:1693)
	at cyder.utilities.UserUtil.checkPassword(UserUtil.java:647)
	at cyder.handlers.internal.LoginHandler.recognize(LoginHandler.java:393)
	at cyder.handlers.internal.LoginHandler.autoCypher(LoginHandler.java:468)
	at cyder.handlers.internal.LoginHandler.beginLogin(LoginHandler.java:365)
	at cyder.genesis.Cyder.main(Cyder.java:112)
[14-45-14] [CORRUPTION]: userdir saved to: [Resulting Popup]
Unfortunately a user's data file was corrupted and had to be deleted. The following files still exists and are associated with the user at the following path:<br/>Cyder/dynamic/5be8c384-7e7d-3540-a615-df8a3cd22bf9<br/>Files:<br/>Default
[14-45-14] [EXCEPTION]: 
Exception origin: cyder.utilities.UserUtil.getUserData(UserUtil.java:469)
From line: 469
Trace: java.lang.IllegalArgumentException: userdata.json does not exist
	at cyder.utilities.UserUtil.getUserData(UserUtil.java:469)
	at cyder.ui.ConsoleFrame.setUUID(ConsoleFrame.java:1695)
	at cyder.utilities.UserUtil.checkPassword(UserUtil.java:647)
	at cyder.handlers.internal.LoginHandler.recognize(LoginHandler.java:393)
	at cyder.handlers.internal.LoginHandler.autoCypher(LoginHandler.java:468)
	at cyder.handlers.internal.LoginHandler.beginLogin(LoginHandler.java:365)
	at cyder.genesis.Cyder.main(Cyder.java:112)
[14-45-14] [EXCEPTION]: 
Exception origin: cyder.utilities.UserUtil.setUserData(UserUtil.java:123)
From line: 123
Trace: java.lang.IllegalArgumentException: File does not exist
	at cyder.utilities.UserUtil.setUserData(UserUtil.java:123)
	at cyder.handlers.internal.LoginHandler.recognize(LoginHandler.java:398)
	at cyder.handlers.internal.LoginHandler.autoCypher(LoginHandler.java:468)
	at cyder.handlers.internal.LoginHandler.beginLogin(LoginHandler.java:365)
	at cyder.genesis.Cyder.main(Cyder.java:112)
[14-45-14] [LOGIN]: [AUTOCYPHER FAIL]
[14-45-14] [WIDGET OPENED]: LOGIN
[14-46-07] [EOL]: Log completed, Cyder was force closed by an external entity: exit code: -200 [External Stop], exceptions thrown: 4