[18-08-57] [ENTRY]: [Nathan]
[18-08-57] [SYSTEM_IO]: System data pared in IOUtil's static block
[18-08-57] [SYSTEM_IO]: Suggestions pared in IOUtil's static block
[18-08-57] [SYSTEM_IO]: Exit conditions pared in IOUtil's static block
[18-08-57] [SYSTEM_IO]: DebugHashes pared in IOUtil's static block
[18-08-59] [LOGIN]: [AUTOCYPHER ATTEMPT]
[18-08-59] [JAVA ARGS]: [LOCATION] [La casa de Nathan]
[18-09-12] [EXCEPTION]: 
Exception origin: cyder.utilities.UserUtil.extractUser(UserUtil.java:407)
From line: 407
Trace: java.lang.IllegalArgumentException: Provided file does not exist
	at cyder.utilities.UserUtil.extractUser(UserUtil.java:407)
	at cyder.ui.CyderFrame.<init>(CyderFrame.java:119)
	at cyder.handlers.internal.PopupHandler.inform(PopupHandler.java:46)
	at cyder.handlers.internal.PopupHandler.inform(PopupHandler.java:26)
	at cyder.handlers.internal.PopupHandler.inform(PopupHandler.java:22)
	at cyder.utilities.UserUtil.userJsonDeleted(UserUtil.java:937)
	at cyder.utilities.UserUtil.fixUser(UserUtil.java:227)
	at cyder.ui.ConsoleFrame.setUUID(ConsoleFrame.java:1693)
	at cyder.utilities.UserUtil.checkPassword(UserUtil.java:648)
	at cyder.handlers.internal.LoginHandler.recognize(LoginHandler.java:393)
	at cyder.handlers.internal.LoginHandler.autoCypher(LoginHandler.java:468)
	at cyder.handlers.internal.LoginHandler.beginLogin(LoginHandler.java:365)
	at cyder.genesis.Cyder.main(Cyder.java:112)
[18-09-12] [CORRUPTION]: userdir saved to: [Resulting Popup]
Unfortunately a user's data file was corrupted and had to be deleted. The following files still exists and are associated with the user at the following path:<br/>Cyder/dynamic/5d5f838e-2cfc-3a60-a36b-26f98ef35cec<br/>Files:<br/>Default
[18-09-23] [EXCEPTION]: 
Exception origin: cyder.utilities.UserUtil.getUserData(UserUtil.java:469)
From line: 469
Trace: java.lang.IllegalArgumentException: userdata.json does not exist
	at cyder.utilities.UserUtil.getUserData(UserUtil.java:469)
	at cyder.ui.ConsoleFrame.setUUID(ConsoleFrame.java:1695)
	at cyder.utilities.UserUtil.checkPassword(UserUtil.java:648)
	at cyder.handlers.internal.LoginHandler.recognize(LoginHandler.java:393)
	at cyder.handlers.internal.LoginHandler.autoCypher(LoginHandler.java:468)
	at cyder.handlers.internal.LoginHandler.beginLogin(LoginHandler.java:365)
	at cyder.genesis.Cyder.main(Cyder.java:112)
[18-09-36] [EXCEPTION]: 
Exception origin: cyder.utilities.UserUtil.setUserData(UserUtil.java:123)
From line: 123
Trace: java.lang.IllegalArgumentException: File does not exist
	at cyder.utilities.UserUtil.setUserData(UserUtil.java:123)
	at cyder.handlers.internal.LoginHandler.recognize(LoginHandler.java:398)
	at cyder.handlers.internal.LoginHandler.autoCypher(LoginHandler.java:468)
	at cyder.handlers.internal.LoginHandler.beginLogin(LoginHandler.java:365)
	at cyder.genesis.Cyder.main(Cyder.java:112)
[18-09-39] [LOGIN]: [AUTOCYPHER FAIL]
[18-09-39] [WIDGET OPENED]: LOGIN
[18-21-17] [EOL]: Log completed, Cyder was force closed by an external entity: exit code: -200 [External Stop], exceptions thrown: 3